// Generated by typings
// Source: src/types/reasonable-router/reasonable-router.d.ts
declare module "reasonable-router";
declare var _BrowserRouter: any;
declare var _ServerRouter: any;
declare var _RouterMountpoint: any;
declare var _Fragment: any;
declare var _Link: any;
declare var _matchRoute: any;
declare function _interopRequireDefault(obj: any): any;
